import type { DemoTrack } from "./demo-catalog.js";
// Second additive batch: official label metadata, reconciled with official video credits/genres.
export const additionalTwenty: readonly DemoTrack[] = [
  {
    title: "Hold You",
    artists: [
      {
        name: "Low Mileage",
        role: "primary",
      },
    ],
    album: "Hold You",
    releaseDate: "2023-10-03",
    videoId: "-ZUUF-J2U4s",
    durationSec: 141,
    language: "Undetermined",
    genres: ["Chill", "Future Trap"],
    source: "https://ncs.io/holdyou",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Driver Seat",
    artists: [
      {
        name: "C1W",
        role: "primary",
      },
    ],
    album: "Driver Seat",
    releaseDate: "2023-07-25",
    videoId: "_zvzWG9tKzI",
    durationSec: 149,
    language: "Undetermined",
    genres: ["Chill", "Deep House"],
    source: "https://ncs.io/driverseat",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Keep Me Closer",
    artists: [
      {
        name: "Low Mileage",
        role: "primary",
      },
    ],
    album: "Keep Me Closer",
    releaseDate: "2023-07-18",
    videoId: "dVteKLjhKFM",
    durationSec: 140,
    language: "Undetermined",
    genres: ["Chill", "Breakbeat"],
    source: "https://ncs.io/keepmecloser",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Where'd You Go",
    artists: [
      {
        name: "Luna Lark",
        role: "featured",
      },
      {
        name: "Julius Dreisig",
        role: "primary",
      },
    ],
    album: "Where'd You Go",
    releaseDate: "2020-04-30",
    videoId: "aWJJEaod34U",
    durationSec: 148,
    language: "Undetermined",
    genres: ["Chill", "Future Bass"],
    source: "https://ncs.io/WYG",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Blindfold",
    artists: [
      {
        name: "Warriyo",
        role: "primary",
      },
      {
        name: "Laura Brehm",
        role: "primary",
      },
    ],
    album: "Blindfold",
    releaseDate: "2025-10-10",
    videoId: "uNRX08JOt6c",
    durationSec: 209,
    language: "Undetermined",
    genres: ["Melodic Dubstep", "Future Trap"],
    source: "https://ncs.io/blindfold",
    releaseSource: "https://ncs.io/music-search?genre=12&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Need You Again",
    artists: [
      {
        name: "SadBois",
        role: "primary",
      },
      {
        name: "ROY KNOX",
        role: "primary",
      },
      {
        name: "Jake Neumar",
        role: "primary",
      },
    ],
    album: "Need You Again",
    releaseDate: "2025-06-24",
    videoId: "Rg6QsFkTmWg",
    durationSec: 237,
    language: "Undetermined",
    genres: ["Melodic Dubstep"],
    source: "https://ncs.io/needyouagain",
    releaseSource: "https://ncs.io/music-search?genre=12&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Dancefloor Dreamer",
    artists: [
      {
        name: "NIVIRO",
        role: "primary",
      },
    ],
    album: "Dancefloor Dreamer",
    releaseDate: "2025-03-14",
    videoId: "NlLaMri0Fow",
    durationSec: 185,
    language: "Undetermined",
    genres: ["Trance"],
    source: "https://ncs.io/DancefloorDreamer",
    releaseSource: "https://ncs.io/music-search?genre=81&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "The Sky High",
    artists: [
      {
        name: "Elektronomia",
        role: "primary",
      },
    ],
    album: "The Sky High",
    releaseDate: "2026-01-02",
    videoId: "cuvGry0ppBA",
    durationSec: 195,
    language: "Undetermined",
    genres: ["Melodic House"],
    source: "https://ncs.io/theskyhigh",
    releaseSource: "https://ncs.io/music-search?genre=54&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Another Way",
    artists: [
      {
        name: "KDH",
        role: "primary",
      },
      {
        name: "Syn Cole",
        role: "primary",
      },
      {
        name: "Vikkstar",
        role: "primary",
      },
      {
        name: "Joe Jury",
        role: "primary",
      },
    ],
    album: "Another Way",
    releaseDate: "2025-02-21",
    videoId: "CTyuZ4qb9a0",
    durationSec: 161,
    language: "Undetermined",
    genres: ["Melodic House", "House"],
    source: "https://ncs.io/AnotherWay",
    releaseSource: "https://ncs.io/music-search?genre=54&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Shake You Off (feat. Shel Bee)",
    artists: [
      {
        name: "Maryn",
        role: "primary",
      },
      {
        name: "Shel Bee",
        role: "featured",
      },
    ],
    album: "Shake You Off (feat. Shel Bee)",
    releaseDate: "2019-03-21",
    videoId: "8Z_IFKjl2Pc",
    durationSec: 229,
    language: "Undetermined",
    genres: ["Indie", "Indie Dance", "Electronic Pop"],
    source: "https://ncs.io/ShakeYouOff",
    releaseSource: "https://ncs.io/music-search?genre=11&display=list&page=3",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Without You",
    artists: [
      {
        name: "Valcos",
        role: "primary",
      },
      {
        name: "Chris Linton",
        role: "primary",
      },
    ],
    album: "Without You",
    releaseDate: "2019-01-23",
    videoId: "wdpGocMoipw",
    durationSec: 157,
    language: "Undetermined",
    genres: ["Indie", "Indie Dance"],
    source: "https://ncs.io/WithoutYou",
    releaseSource: "https://ncs.io/music-search?genre=11&display=list&page=3",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Round n' Round",
    artists: [
      {
        name: "Shiah Maisel",
        role: "primary",
      },
      {
        name: "Clarx",
        role: "primary",
      },
    ],
    album: "Round n' Round",
    releaseDate: "2024-03-22",
    videoId: "WmyLI61sa9I",
    durationSec: 223,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/RoundNRound",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Left With Nothing",
    artists: [
      {
        name: "Clarx",
        role: "primary",
      },
      {
        name: "Shiah Maisel",
        role: "primary",
      },
    ],
    album: "Left With Nothing",
    releaseDate: "2024-02-23",
    videoId: "IGkW7l-0ptE",
    durationSec: 217,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/LeftWithNothing",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Romeo and Juliet",
    artists: [
      {
        name: "SadBois",
        role: "primary",
      },
      {
        name: "Manno",
        role: "primary",
      },
    ],
    album: "Romeo and Juliet",
    releaseDate: "2024-02-22",
    videoId: "zNGqtG4tjzQ",
    durationSec: 192,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/RnJ",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Vienna (feat. PhiloSofie)",
    artists: [
      {
        name: "James Mercy",
        role: "primary",
      },
      {
        name: "PhiloSofie",
        role: "featured",
      },
    ],
    album: "Vienna (feat. PhiloSofie)",
    releaseDate: "2023-12-29",
    videoId: "wJ0VVutDj4I",
    durationSec: 214,
    language: "Undetermined",
    genres: ["Electronic Rock", "Trap"],
    source: "https://ncs.io/Vienna",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "ILYBB",
    artists: [
      {
        name: "Ailow",
        role: "primary",
      },
      {
        name: "Dionysus",
        role: "primary",
      },
    ],
    album: "ILYBB",
    releaseDate: "2025-09-18",
    videoId: "REzVa8a-Mzk",
    durationSec: 143,
    language: "Undetermined",
    genres: ["Hardstyle"],
    source: "https://ncs.io/A_ILYBB",
    releaseSource: "https://ncs.io/music-search?genre=9&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "On My Mind",
    artists: [
      {
        name: "No Hero",
        role: "primary",
      },
    ],
    album: "On My Mind",
    releaseDate: "2024-11-26",
    videoId: "lb6jG08lRy8",
    durationSec: 166,
    language: "Undetermined",
    genres: ["Hardstyle", "Happy Hardcore"],
    source: "https://ncs.io/OnMyMind",
    releaseSource: "https://ncs.io/music-search?genre=9&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Complicated",
    artists: [
      {
        name: "WBN",
        role: "primary",
      },
      {
        name: "WIBERG",
        role: "primary",
      },
    ],
    album: "Complicated",
    releaseDate: "2022-03-22",
    videoId: "tnRxocc7PpA",
    durationSec: 160,
    language: "Undetermined",
    genres: ["Glitch Hop"],
    source: "https://ncs.io/Complicated",
    releaseSource: "https://ncs.io/music-search?genre=15&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Alive",
    artists: [
      {
        name: "Tamlin",
        role: "primary",
      },
    ],
    album: "Alive",
    releaseDate: "2025-05-13",
    videoId: "AeIK7C6iNsQ",
    durationSec: 224,
    language: "Undetermined",
    genres: ["Disco"],
    source: "https://ncs.io/T_Alive",
    releaseSource: "https://ncs.io/music-search?genre=45&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
  {
    title: "Boogie",
    artists: [
      {
        name: "Joyful",
        role: "primary",
      },
      {
        name: "Фрози",
        role: "primary",
      },
      {
        name: "Zachz Winner",
        role: "primary",
      },
    ],
    album: "Boogie",
    releaseDate: "2025-01-31",
    videoId: "kbfhyc5_y3U",
    durationSec: 123,
    language: "Undetermined",
    genres: ["Disco", "Discoplug"],
    source: "https://ncs.io/Boogie",
    releaseSource: "https://ncs.io/music-search?genre=45&display=list&page=1",
    checkedAt: "2026-09-19T02:01:21.902Z",
  },
];
