import type { DemoTrack } from "./demo-catalog.js";
// Label catalog credits/genres and release dates, reconciled with the official video title.
// Undetermined means the language has not been independently confirmed.
export const catalogAdditions: readonly DemoTrack[] = [
  {
    title: "Severed Rose",
    artists: [
      {
        name: "SlidV",
        role: "primary",
      },
      {
        name: "Clarx",
        role: "primary",
      },
    ],
    album: "Severed Rose",
    releaseDate: "2024-12-05",
    videoId: "aZ6-xptxwF0",
    durationSec: 157,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/SeveredRose",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Notice That",
    artists: [
      {
        name: "Zaug",
        role: "primary",
      },
    ],
    album: "Notice That",
    releaseDate: "2024-10-15",
    videoId: "zGqg6kDhDxI",
    durationSec: 123,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/NoticeThat",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Happier Now",
    artists: [
      {
        name: "Gabriel Eli",
        role: "primary",
      },
      {
        name: "SadBois",
        role: "primary",
      },
    ],
    album: "Happier Now",
    releaseDate: "2024-10-03",
    videoId: "jTGcGcUquqk",
    durationSec: 180,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/HappierNow",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Time Is Eating",
    artists: [
      {
        name: "Unlike Pluto",
        role: "primary",
      },
    ],
    album: "Time Is Eating",
    releaseDate: "2024-08-01",
    videoId: "Xz2fDknGVZs",
    durationSec: 185,
    language: "Undetermined",
    genres: ["Electronic Rock", "Drumstep"],
    source: "https://ncs.io/TimeIsEating",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "The Right Time",
    artists: [
      {
        name: "LUVIUM",
        role: "primary",
      },
      {
        name: "Youth In Circles",
        role: "primary",
      },
    ],
    album: "The Right Time",
    releaseDate: "2024-06-06",
    videoId: "ygmwOraoC8s",
    durationSec: 276,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/TheRightTime",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Gotta Leave",
    artists: [
      {
        name: "Shiah Maisel",
        role: "primary",
      },
      {
        name: "Clarx",
        role: "primary",
      },
    ],
    album: "Gotta Leave",
    releaseDate: "2024-04-19",
    videoId: "9HRIZA6phIY",
    durationSec: 157,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/GottaLeave",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Along Your Way",
    artists: [
      {
        name: "Pala Chrome",
        role: "primary",
      },
      {
        name: "Dust of Apollon",
        role: "primary",
      },
    ],
    album: "Along Your Way",
    releaseDate: "2024-04-04",
    videoId: "xOWPx1nN2oE",
    durationSec: 295,
    language: "Undetermined",
    genres: ["Electronic Rock"],
    source: "https://ncs.io/AlongYourWay",
    releaseSource: "https://ncs.io/music-search?genre=83&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Only The Fallen",
    artists: [
      {
        name: "Zeli",
        role: "primary",
      },
    ],
    album: "Only The Fallen",
    releaseDate: "2024-03-07",
    videoId: "HipT91U3ujA",
    durationSec: 196,
    language: "Undetermined",
    genres: ["Techno", "Pop", "Electronic", "Tech House"],
    source: "https://ncs.io/OnlyTheFallen",
    releaseSource: "https://ncs.io/music-search?genre=19&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "What's The Problem?",
    artists: [
      {
        name: "OSKI",
        role: "primary",
      },
    ],
    album: "What's The Problem?",
    releaseDate: "2023-12-14",
    videoId: "aP-XK5fxdcs",
    durationSec: 149,
    language: "Undetermined",
    genres: ["Electronic", "Pop"],
    source: "https://ncs.io/WTP",
    releaseSource: "https://ncs.io/music-search?genre=19&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Karma",
    artists: [
      {
        name: "Alaina Cross",
        role: "primary",
      },
    ],
    album: "Karma",
    releaseDate: "2023-11-10",
    videoId: "MRvty0llojA",
    durationSec: 189,
    language: "Undetermined",
    genres: ["Pop", "Electronic"],
    source: "https://ncs.io/karma",
    releaseSource: "https://ncs.io/music-search?genre=19&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Don't Understand",
    artists: [
      {
        name: "Sketchez",
        role: "primary",
      },
    ],
    album: "Don't Understand",
    releaseDate: "2023-10-24",
    videoId: "cY0qzUnM2ME",
    durationSec: 139,
    language: "Undetermined",
    genres: ["Pop"],
    source: "https://ncs.io/dontunderstand",
    releaseSource: "https://ncs.io/music-search?genre=19&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Cruising",
    artists: [
      {
        name: "Aisake",
        role: "primary",
      },
      {
        name: "Dosi",
        role: "primary",
      },
    ],
    album: "Cruising",
    releaseDate: "2024-03-26",
    videoId: "qjElWBGZou4",
    durationSec: 160,
    language: "Undetermined",
    genres: ["Lofi Hip-Hop"],
    source: "https://ncs.io/Cruising",
    releaseSource: "https://ncs.io/music-search?genre=60&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "apart",
    artists: [
      {
        name: "sumu",
        role: "primary",
      },
    ],
    album: "apart",
    releaseDate: "2024-02-27",
    videoId: "ihPTNp7370s",
    durationSec: 142,
    language: "Undetermined",
    genres: ["Lofi Hip-Hop"],
    source: "https://ncs.io/apart",
    releaseSource: "https://ncs.io/music-search?genre=60&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "harinezumi",
    artists: [
      {
        name: "waera",
        role: "primary",
      },
    ],
    album: "harinezumi",
    releaseDate: "2025-02-14",
    videoId: "lZ1fj36B42g",
    durationSec: 117,
    language: "Undetermined",
    genres: ["Nu-Jazz"],
    source: "https://ncs.io/harinezumi",
    releaseSource: "https://ncs.io/music-search?genre=87&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Missing Life",
    artists: [
      {
        name: "gabriawll",
        role: "primary",
      },
      {
        name: "QKReign",
        role: "primary",
      },
    ],
    album: "Missing Life",
    releaseDate: "2025-05-28",
    videoId: "AbnPScMYQes",
    durationSec: 124,
    language: "Undetermined",
    genres: ["RnB", "Jersey Club"],
    source: "https://ncs.io/missinglife",
    releaseSource: "https://ncs.io/music-search?genre=88&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Nobody Around",
    artists: [
      {
        name: "Rival",
        role: "primary",
      },
      {
        name: "Biometrix",
        role: "primary",
      },
      {
        name: "CRVN",
        role: "primary",
      },
    ],
    album: "Nobody Around",
    releaseDate: "2026-08-20",
    videoId: "JpyFodlr1fc",
    durationSec: 199,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/NobodyAround",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Set Me Free",
    artists: [
      {
        name: "Rameses B",
        role: "primary",
      },
    ],
    album: "Set Me Free",
    releaseDate: "2025-10-07",
    videoId: "qzoHRNMVXns",
    durationSec: 235,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/RB_setmefree",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Uncharted",
    artists: [
      {
        name: "NIVIRO",
        role: "primary",
      },
      {
        name: "Nathalie Blue",
        role: "featured",
      },
    ],
    album: "Uncharted",
    releaseDate: "2025-09-11",
    videoId: "ep9a-R_VgoY",
    durationSec: 188,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/N_Uncharted",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Do It All",
    artists: [
      {
        name: "Rameses B",
        role: "primary",
      },
      {
        name: "Southby",
        role: "primary",
      },
      {
        name: "Wigal",
        role: "primary",
      },
    ],
    album: "Do It All",
    releaseDate: "2025-09-02",
    videoId: "S086etZ3Tq8",
    durationSec: 208,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/RB_doitall",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "All We've Ever Known (ft. Fred V & Immy Odon)",
    artists: [
      {
        name: "Cartoon",
        role: "primary",
      },
      {
        name: "Fred V",
        role: "primary",
      },
      {
        name: "Immy Odon",
        role: "primary",
      },
    ],
    album: "All We've Ever Known (ft. Fred V & Immy Odon)",
    releaseDate: "2025-08-29",
    videoId: "StNj6WFsqf4",
    durationSec: 160,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/allweveeverknown",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Another Life",
    artists: [
      {
        name: "Karyuu",
        role: "primary",
      },
      {
        name: "Jaylenn",
        role: "primary",
      },
    ],
    album: "Another Life",
    releaseDate: "2025-08-26",
    videoId: "d9CnJGpY65I",
    durationSec: 240,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/AnotherLife",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Only Human",
    artists: [
      {
        name: "ThatBehavior",
        role: "primary",
      },
    ],
    album: "Only Human",
    releaseDate: "2025-08-05",
    videoId: "mdHnp18qlgc",
    durationSec: 135,
    language: "Undetermined",
    genres: ["Drum & Bass"],
    source: "https://ncs.io/onlyhuman",
    releaseSource: "https://ncs.io/music-search?genre=3&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Talk",
    artists: [
      {
        name: "Beave",
        role: "primary",
      },
    ],
    album: "Talk",
    releaseDate: "2022-02-24",
    videoId: "uZi8_rnqgHg",
    durationSec: 182,
    language: "Undetermined",
    genres: ["Chill"],
    source: "https://ncs.io/Talk",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Symphony",
    artists: [
      {
        name: "Donna Tella",
        role: "featured",
      },
      {
        name: "Arc North",
        role: "primary",
      },
    ],
    album: "Symphony",
    releaseDate: "2021-09-17",
    videoId: "E6HlSLZVR1g",
    durationSec: 194,
    language: "Undetermined",
    genres: ["Chill"],
    source: "https://ncs.io/Symphony",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Crazy",
    artists: [
      {
        name: "Frizzy The Streetz",
        role: "primary",
      },
      {
        name: "Simbai",
        role: "primary",
      },
    ],
    album: "Crazy",
    releaseDate: "2021-08-13",
    videoId: "-aSuZsRsOys",
    durationSec: 181,
    language: "Undetermined",
    genres: ["Chill"],
    source: "https://ncs.io/SCrazy",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Higher",
    artists: [
      {
        name: "Vanessa Campagna",
        role: "featured",
      },
      {
        name: "Hoober",
        role: "primary",
      },
    ],
    album: "Higher",
    releaseDate: "2021-03-11",
    videoId: "RBPuDWzZUiA",
    durationSec: 173,
    language: "Undetermined",
    genres: ["Chill"],
    source: "https://ncs.io/HHigher",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Like Me",
    artists: [
      {
        name: "Britt Lari",
        role: "primary",
      },
      {
        name: "T-Mass",
        role: "primary",
      },
    ],
    album: "Like Me",
    releaseDate: "2020-10-20",
    videoId: "iQrYoJ5tRV8",
    durationSec: 212,
    language: "Undetermined",
    genres: ["Chill", "Trap", "Electronic"],
    source: "https://ncs.io/LikeMe",
    releaseSource: "https://ncs.io/music-search?genre=2&display=list",
    checkedAt: "2026-09-19T01:33:57.207Z",
  },
  {
    title: "Avatar",
    artists: [
      {
        name: "RYVN",
        role: "primary",
      },
    ],
    album: "Avatar",
    releaseDate: "2022-03-04",
    videoId: "WUL0hSLFbTA",
    durationSec: 154,
    language: "Undetermined",
    genres: ["Trap"],
    source: "https://ncs.io/Avatar",
    releaseSource: "https://ncs.io/music-search?genre=14&display=list&page=2",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Take Our Time",
    artists: [
      {
        name: "Tollef",
        role: "primary",
      },
    ],
    album: "Take Our Time",
    releaseDate: "2022-02-22",
    videoId: "uFkzXH9t2cA",
    durationSec: 154,
    language: "Undetermined",
    genres: ["Indie", "Indie Dance"],
    source: "https://ncs.io/TakeOurTime",
    releaseSource: "https://ncs.io/music-search?genre=11&display=list&page=2",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Dreaming Of Me",
    artists: [
      {
        name: "Jack Shore",
        role: "primary",
      },
      {
        name: "Tollef",
        role: "primary",
      },
      {
        name: "Jaime Deraz",
        role: "featured",
      },
    ],
    album: "Dreaming Of Me",
    releaseDate: "2021-11-02",
    videoId: "j6hvDAOaX_M",
    durationSec: 199,
    language: "Undetermined",
    genres: ["Indie", "Indie Dance"],
    source: "https://ncs.io/DreamingOfMe",
    releaseSource: "https://ncs.io/music-search?genre=11&display=list&page=2",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Moonlight",
    artists: [
      {
        name: "Jim Yosef",
        role: "primary",
      },
    ],
    album: "Moonlight",
    releaseDate: "2019-03-01",
    videoId: "MvTYrjX4ve4",
    durationSec: 215,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/Moonlight",
    releaseSource: "https://ncs.io/music-search?genre=10&display=list&page=6",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Clear My Head",
    artists: [
      {
        name: "Ellis",
        role: "primary",
      },
    ],
    album: "Clear My Head",
    releaseDate: "2019-02-18",
    videoId: "H81DzDMdCLI",
    durationSec: 217,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/ClearMyHead",
    releaseSource: "https://ncs.io/music-search?genre=10&display=list&page=6",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Return To The Wild",
    artists: [
      {
        name: "Tobu",
        role: "primary",
      },
    ],
    album: "Return To The Wild",
    releaseDate: "2018-11-30",
    videoId: "C7eIj9_9H2U",
    durationSec: 198,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/ReturnToTheWild",
    releaseSource: "https://ncs.io/music-search?genre=10&display=list&page=6",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Muffin",
    artists: [
      {
        name: "Raven & Kreyn",
        role: "primary",
      },
    ],
    album: "Muffin",
    releaseDate: "2018-11-09",
    videoId: "rc5SMO5bvx0",
    durationSec: 161,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/Muffin",
    releaseSource: "https://ncs.io/music-search?genre=10&display=list&page=6",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
  {
    title: "Power",
    artists: [
      {
        name: "ELPORT",
        role: "primary",
      },
      {
        name: "VYMVN",
        role: "primary",
      },
    ],
    album: "Power",
    releaseDate: "2018-11-05",
    videoId: "ab2y9VP1_6s",
    durationSec: 155,
    language: "Undetermined",
    genres: ["House"],
    source: "https://ncs.io/Power",
    releaseSource: "https://ncs.io/music-search?genre=10&display=list&page=6",
    checkedAt: "2026-09-19T01:35:18.204Z",
  },
];
